In [4]:
!pip install tensorflow==2.0.0-beta-1

     |████████████████████████████████| 87.9MB 1.3MB/s 
     |████████████████████████████████| 3.1MB 39.7MB/s 
     |████████████████████████████████| 501kB 40.5MB/s 
  Found existing installation: tensorflow 1.14.0
    Uninstalling tensorflow-1.14.0:
      Successfully uninstalled tensorflow-1.14.0


In [0]:
import tensorflow as tf 
import numpy as np

In [2]:
tf.__version__

'2.0.0-beta1'

# Constants

**Defining a Constant:**

In [0]:
# Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23,4],[32,51]])

In [4]:
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [5]:
#getting the shape of a tensor
tensor_20.shape

TensorShape([2, 2])

**Getting the values of  constant**

In [6]:
## Getting the values straight from a TensorFlow constant with numpy, and without the need of a session
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
# We are able to convert a numpy array back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,4],[32,51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [9]:
tensor_from_numpy

<tf.Tensor: id=3, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

# Variables

**Defining a Variable:**

In [10]:
tf2_variable = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

**Getting the values of a variable**

In [11]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

**Changing a specific value of a Variable**

In [14]:
tf2_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [15]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

**Operations with Tensors:**

In [16]:
tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: id=34, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

**Addition between a scalar and a tensor:**

In [17]:
tensor+2

<tf.Tensor: id=37, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

**Multiplication between a scalar and a tensor**

In [18]:
tensor*5

<tf.Tensor: id=40, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

**Using Numpy functions on TensorFlow tensors**

In [20]:
#getting the squares of all numbers in a TensorFlow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [21]:
#Getting the square root of all number in a tensroflow tensor object

np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

**Dot product between two tensors**

In [22]:
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

**Strings in TensorFlow 2.0**

In [23]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=42, shape=(), dtype=string, numpy=b'TensorFlow'>

In [26]:
tf_string.numpy()

b'TensorFlow'

**Simple String Operations**

In [27]:
tf.strings.length(tf_string)

<tf.Tensor: id=46, shape=(), dtype=int32, numpy=10>

In [28]:
tf.strings.unicode_decode(tf_string,"UTF8")

<tf.Tensor: id=51, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

**Storing Arrays of Strings**

In [0]:
tf_string_array = tf.constant(['TensorFlow',"Deep Learning","AI"])

In [41]:
# Iterating through the TF string array
for x in tf_string_array:
    print(x)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
